/*
    Project VITAL.Dashboard
    Copyright (C) 2017 - Universiteit Hasselt
    This project has been funded with support from the European Commission (Project number: 2015-BE02-KA203-012317). 

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LMG.Infrastructure.Analytics.Objects.Types
{
    public enum CustomXAPIDefinitionExtensions
    {
        InstanceId,
        AttemptMax,
        DragId,
        DragCaption,
        DragCaptionValueType,
        DropTargetId,
        DropTargetHotspotName,
        ExerciseType,
        MimeType,
        DictionaryId, 
        TabTitle, 
        DictionaryEntryId,
        DictionarySearchOption,
        DictionarySearchTerm,
        HintId,
        SolutionId,
        FeedbackId,
        CorrectAnswers,
        NavigationType,
        IsVoiceRecording,
        AccessType,
        DictionarySearchResultCount,
        ExploreHotspotId,
        ExploreHotspotTabId,
        ExploreHotspotTabCount,
        SentenceId,
        IsAutogenerated,
        MigrateSessionTo,
        PlatformVersion
    }
    
    public static class CustomXAPIDefinitionExtensionsConverter
    {
        public static string Convert(CustomXAPIDefinitionExtensions value)
        {
            switch (value)
            {
                case CustomXAPIDefinitionExtensions.InstanceId:                     return "extension/instance-id";
                case CustomXAPIDefinitionExtensions.AttemptMax:                     return "extension/attempt-max";
                case CustomXAPIDefinitionExtensions.DragId:                         return "extension/drag-id";
                case CustomXAPIDefinitionExtensions.DragCaption:                    return "extension/drag-caption";
                case CustomXAPIDefinitionExtensions.DragCaptionValueType:           return "extension/drag-caption-value-type";
                case CustomXAPIDefinitionExtensions.DropTargetId:                   return "extension/drop-target-id";
                case CustomXAPIDefinitionExtensions.DropTargetHotspotName:          return "extension/drop-target-hotspot-name";
                case CustomXAPIDefinitionExtensions.ExerciseType:                   return "extension/exercise-type";
                case CustomXAPIDefinitionExtensions.MimeType:                       return "extension/mime-type";
                case CustomXAPIDefinitionExtensions.DictionaryId:                   return "extension/dictionary-id";
                case CustomXAPIDefinitionExtensions.TabTitle:                       return "extension/tab-title";
                case CustomXAPIDefinitionExtensions.DictionaryEntryId:              return "extension/dictionary-entry-id";
                case CustomXAPIDefinitionExtensions.DictionarySearchOption:         return "extension/dictionary-search-option";
                case CustomXAPIDefinitionExtensions.DictionarySearchTerm:           return "extension/dictionary-search-term";
                case CustomXAPIDefinitionExtensions.DictionarySearchResultCount:    return "extension/dictionary-search-result-count";
                case CustomXAPIDefinitionExtensions.HintId:                         return "extension/hint-id";
                case CustomXAPIDefinitionExtensions.SolutionId:                     return "extension/solution-id";
                case CustomXAPIDefinitionExtensions.FeedbackId:                     return "extension/feedback-id";
                case CustomXAPIDefinitionExtensions.CorrectAnswers:                 return "extension/correct-answers";
                case CustomXAPIDefinitionExtensions.NavigationType:                 return "extension/navigation-type";
                case CustomXAPIDefinitionExtensions.IsVoiceRecording:               return "extension/is-voice-recording";
                case CustomXAPIDefinitionExtensions.AccessType:                     return "extension/access-type";
                case CustomXAPIDefinitionExtensions.ExploreHotspotId:               return "extension/explore-hotspot-id";
                case CustomXAPIDefinitionExtensions.ExploreHotspotTabId:            return "extension/explore-hotspot-tab-id";
                case CustomXAPIDefinitionExtensions.ExploreHotspotTabCount:         return "extension/explore-hotspot-tab-count";
                case CustomXAPIDefinitionExtensions.SentenceId:                     return "extension/sentence-id";
                case CustomXAPIDefinitionExtensions.IsAutogenerated:                return "extension/is-autogenerated";
                case CustomXAPIDefinitionExtensions.MigrateSessionTo:               return "extension/session-migration-to";
                case CustomXAPIDefinitionExtensions.PlatformVersion:                return "extension/platform-version";
                default: return null;
            }
        }
    }

}
